// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZX3CvOQkHWOPAfJppHNs4ZK-tVBi8u6M',
    appId: '1:327053328438:web:146a41e159ea061b29d897',
    messagingSenderId: '327053328438',
    projectId: 'svnapp-18de1',
    authDomain: 'svnapp-18de1.firebaseapp.com',
    storageBucket: 'svnapp-18de1.appspot.com',
    measurementId: 'G-H4QFY63VRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgkwn4j4AVlhdtP2n1LFsD8AgmeKLk1U',
    appId: '1:327053328438:android:8a37d033aa2c5bdb29d897',
    messagingSenderId: '327053328438',
    projectId: 'svnapp-18de1',
    storageBucket: 'svnapp-18de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCDnw3Botnbf-Nq3kJoXNWkx3iPGV6KsQ',
    appId: '1:327053328438:ios:f91d733f77443a3429d897',
    messagingSenderId: '327053328438',
    projectId: 'svnapp-18de1',
    storageBucket: 'svnapp-18de1.appspot.com',
    iosClientId: '327053328438-hkvpefpkub6a21nsjr7h1814618a54qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCDnw3Botnbf-Nq3kJoXNWkx3iPGV6KsQ',
    appId: '1:327053328438:ios:f91d733f77443a3429d897',
    messagingSenderId: '327053328438',
    projectId: 'svnapp-18de1',
    storageBucket: 'svnapp-18de1.appspot.com',
    iosClientId: '327053328438-hkvpefpkub6a21nsjr7h1814618a54qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZX3CvOQkHWOPAfJppHNs4ZK-tVBi8u6M',
    appId: '1:327053328438:web:0bb9cadf4355b39629d897',
    messagingSenderId: '327053328438',
    projectId: 'svnapp-18de1',
    authDomain: 'svnapp-18de1.firebaseapp.com',
    storageBucket: 'svnapp-18de1.appspot.com',
    measurementId: 'G-ME81JBNFJJ',
  );
}
